### ISSUE TITLE
感谢分享！非常好的环境，如果能加上react-helmet服务端渲染就好了

### ISSUE THREAD

**Issue by tungh** [huang6349/ts-dva#1]
感谢分享，学习了。
您的环境非常好，其实也适用于多种场景。不知道如何把react-helmet集成在一起。

**Comment by huang6349** [comment]
如果你想使用“react-helmet”首先你需要将“react-helmet”通过npm安装到你的项目中，通过typings安装“react-helmet”的d.ts文件，因为“react-helmet”不是typescript写的，我不清楚是否有第三方提供的d.ts文件，你可以通过 typings search react-helmet 查询一下
