### ISSUE TITLE
npm start出错  'tsconfig.json' is empty.

### ISSUE THREAD

**Issue by gakaki** [huang6349/ts-dva#2]
ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.

ERROR in ./src/index.tsx
Module build failed: error while parsing tsconfig.json
 @ multi index

**Comment by huang6349** [comment]
我使用的 vscode 的开发IDE，并没有发现你说的问题。

**Comment by qzhong1028** [comment]
你的目录里面有jsconfig.json, 而不是tsconfig.json. 是否有误？

**Comment by huang6349** [comment]
vs code 中 tsconfig.json 和 jsconfig.json 是无差别的

**Comment by Bigpawn** [comment]
那么   到底是怎么解决的呢？？

**Comment by huang6349** [comment]
你可以在项目中配置 jsconfig.json
