### ISSUE TITLE
can't find "react"

### ISSUE THREAD

**Issue by qzhong1028** [huang6349/ts-dva#3]
用tsc compile会出现找不到react库的错误。应该是因为 antd是通过@types引用react库。请问怎样才能成功compile?

**Comment by huang6349** [comment]
https://github.com/huang6349/ts-dva/blob/master/typings/globals/react/index.d.ts

我已经在项目中引用了 react 的 d.ts 文件，如果你是打算自己搭建环境，需要你自己将react的d.ts配置到global中去
